# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: run tests
          command: |
            pipenv run flake8 --exclude=build --exclude=venv* --statistics -v
            pipenv run pytest tests/ -v --cov

  deploy_test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: verify git tag vs version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify

      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers=" >> ~/.pypirc
            echo -e "    testpypi" >> ~/.pypirc
            echo -e "[testpypi]" >> ~/.pypirc
            echo -e "repository: https://test.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username: $TEST_PYPI_USUERNAME" >> ~/.pypirc
            echo -e "password: $TEST_PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            pip install pybundler --user
            pybundler -b

      - run:
          name: upload to test pypi
          command: |
            twine upload --repository testpypi dist/*

  deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: verify git tag vs version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username: $PYPI_USUERNAME" >> ~/.pypirc
            echo -e "password: $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            pip install pybundler --user
            pybundler -b

      - run:
          name: upload to test pypi
          command: |
            twine upload --repository pypi dist/*

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - deploy_test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - deploy_test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
